spring:
    profiles:
        active: local

---
spring:
    profiles: local
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                format_sql: true
        hibernate:
            ddl-auto: create

---
spring:
    profiles: deploy
    jpa:
        database: mysql
        hibernate.ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    datasource:
        url: jdbc:mysql://localhost:13306/caffeine?serverTimezone=UTC
        username: ed
        password: password