spring:
  profiles:
    active: local

## local
---
spring:
  profiles: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    data: classpath:data.sql
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

## deploy
---
spring:
  profiles: deploy
server:
  port: 8080

## mysql
---

