name: CI-Backend

on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: execute build
        run: |
          docker build . --file Dockerfile --tag kangmin46/backend:latest
      - name: docker login
        run: |
          docker login -u ${{secrets.DOCKER_USER_NAME}} --password ${{secrets.DOCKER_USER_PASSWORD}}
          docker push kangmin46/backend:latest
